ASP_Final/Models/AUTHOR.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_Final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUTHOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AUTHOR()
        {
            this.WROTE = new HashSet<WROTE>();
            this.WROTE1 = new HashSet<WROTE>();
            this.WROTE2 = new HashSet<WROTE>();
        }
    
        public int AUTHOR_NUM { get; set; }
        public string AUTHOR_LAST { get; set; }
        public string AUTHOR_FIRST { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WROTE> WROTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WROTE> WROTE1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WROTE> WROTE2 { get; set; }
    }
}

ASP_Final/Models/Contact.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ASP_Final.Models
{
    public class Contact
    {
        public string FName { get; set; }

        public string LName { get; set; }

        public string Email { get; set; }

        public string ConfirmEmail { get; set; }

        public string Branch { get; set; }

        public string Comments { get; set; }

    }
}

ASP_Final/Models/PUBLISHER.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_Final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUBLISHER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PUBLISHER()
        {
            this.BOOK = new HashSet<BOOK>();
            this.BOOK1 = new HashSet<BOOK>();
            this.BOOK2 = new HashSet<BOOK>();
        }
    
        public string PUBLISHER_CODE { get; set; }
        public string PUBLISHER_NAME { get; set; }
        public string CITY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOOK> BOOK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOOK> BOOK1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOOK> BOOK2 { get; set; }
    }
}

ASP_Final/Controllers/BOOKsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ASP_Final.Models;

namespace ASP_Final.Controllers
{
    public class BOOKsController : Controller
    {
        private HenryEntities db = new HenryEntities();

        // GET: BOOKs
        public ActionResult Index()
        {
            var bOOK = db.BOOK.Include(b => b.PUBLISHER).Include(b => b.PUBLISHER1).Include(b => b.PUBLISHER2);
            return View(bOOK.ToList());
        }

        // GET: BOOKs/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BOOK bOOK = db.BOOK.Find(id);
            if (bOOK == null)
            {
                return HttpNotFound();
            }
            return View(bOOK);
        }

        // GET: BOOKs/Create
        public ActionResult Create()
        {
            ViewBag.PUBLISHER_CODE = new SelectList(db.PUBLISHER, "PUBLISHER_CODE", "PUBLISHER_NAME");
            ViewBag.PUBLISHER_CODE = new SelectList(db.PUBLISHER, "PUBLISHER_CODE", "PUBLISHER_NAME");
            ViewBag.PUBLISHER_CODE = new SelectList(db.PUBLISHER, "PUBLISHER_CODE", "PUBLISHER_NAME");
            return View();
        }

        // POST: BOOKs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "BOOK_CODE,TITLE,PUBLISHER_CODE,TYPE,PRICE,PAPERBACK")] BOOK bOOK)
        {
            if (ModelState.IsValid)
            {
                db.BOOK.Add(bOOK);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.PUBLISHER_CODE = new SelectList(db.PUBLISHER, "PUBLISHER_CODE", "PUBLISHER_NAME", bOOK.PUBLISHER_CODE);
            ViewBag.PUBLISHER_CODE = new SelectList(db.PUBLISHER, "PUBLISHER_CODE", "PUBLISHER_NAME", bOOK.PUBLISHER_CODE);
            ViewBag.PUBLISHER_CODE = new SelectList(db.PUBLISHER, "PUBLISHER_CODE", "PUBLISHER_NAME", bOOK.PUBLISHER_CODE);
            return View(bOOK);
        }

        // GET: BOOKs/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BOOK bOOK = db.BOOK.Find(id);
            if (bOOK == null)
            {
                return HttpNotFound();
            }
            ViewBag.PUBLISHER_CODE = new SelectList(db.PUBLISHER, "PUBLISHER_CODE", "PUBLISHER_NAME", bOOK.PUBLISHER_CODE);
            ViewBag.PUBLISHER_CODE = new SelectList(db.PUBLISHER, "PUBLISHER_CODE", "PUBLISHER_NAME", bOOK.PUBLISHER_CODE);
            ViewBag.PUBLISHER_CODE = new SelectList(db.PUBLISHER, "PUBLISHER_CODE", "PUBLISHER_NAME", bOOK.PUBLISHER_CODE);
            return View(bOOK);
        }

        // POST: BOOKs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "BOOK_CODE,TITLE,PUBLISHER_CODE,TYPE,PRICE,PAPERBACK")] BOOK bOOK)
        {
            if (ModelState.IsValid)
            {
                db.Entry(bOOK).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.PUBLISHER_CODE = new SelectList(db.PUBLISHER, "PUBLISHER_CODE", "PUBLISHER_NAME", bOOK.PUBLISHER_CODE);
            ViewBag.PUBLISHER_CODE = new SelectList(db.PUBLISHER, "PUBLISHER_CODE", "PUBLISHER_NAME", bOOK.PUBLISHER_CODE);
            ViewBag.PUBLISHER_CODE = new SelectList(db.PUBLISHER, "PUBLISHER_CODE", "PUBLISHER_NAME", bOOK.PUBLISHER_CODE);
            return View(bOOK);
        }

        // GET: BOOKs/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BOOK bOOK = db.BOOK.Find(id);
            if (bOOK == null)
            {
                return HttpNotFound();
            }
            return View(bOOK);
        }

        // POST: BOOKs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            BOOK bOOK = db.BOOK.Find(id);
            db.BOOK.Remove(bOOK);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ASP_Final/Controllers/BrowseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ASP_Final.Models;

namespace ASP_Final.Controllers
{
    public class BrowseController : Controller
    {
        private HenryEntities db = new HenryEntities();

        public ActionResult Index()
        {
            Browse model = new Browse();
            model.AllAuthorOptions = db.AUTHOR.OrderBy(s => s.AUTHOR_LAST).ToList().Select(c => new SelectListItem()
            {
                Text = c.AUTHOR_LAST + ", " + c.AUTHOR_FIRST,
                Value = c.AUTHOR_NUM.ToString()
            });
            return PartialView("~/Views/Shared/_Author.cshtml", model);
        }

        [HttpPost]
        public ActionResult Index(Browse model)
        {
            model.AllAuthorOptions = db.AUTHOR.OrderBy(s => s.AUTHOR_LAST).ToList().Select(c => new SelectListItem()
            {
                Text = c.AUTHOR_LAST + ", " + c.AUTHOR_FIRST,
                Value = c.AUTHOR_NUM.ToString()
            });
            return PartialView("~/Views/Shared/_Author.cshtml", model);
        }

        public ActionResult Publisher()
        {
            Browse model = new Browse();
            model.AllPublisherOptions = db.PUBLISHER.OrderBy(s => s.PUBLISHER_NAME).ToList().Select(c => new SelectListItem()
            {
                Text = c.PUBLISHER_NAME,
                Value = c.PUBLISHER_CODE.ToString()
            });
            return PartialView("~/Views/Shared/_Publisher.cshtml", model);
        }

        [HttpPost]
        public ActionResult Publisher(Browse model)
        {
            model.AllPublisherOptions = db.PUBLISHER.OrderBy(s => s.PUBLISHER_NAME).ToList().Select(c => new SelectListItem()
            {
                Text = c.PUBLISHER_NAME,
                Value = c.PUBLISHER_CODE.ToString()
            });
            return PartialView("~/Views/Shared/_Publisher.cshtml", model);
        }

        public ActionResult Location()
        {
            Browse model = new Browse();
            model.AllLocationOptions = db.BRANCH.OrderBy(s => s.BRANCH_NAME).ToList().Select(c => new SelectListItem()
            {
                Text = c.BRANCH_NAME,
                Value = c.BRANCH_NUM.ToString()
            });
            return PartialView("~/Views/Shared/_Location.cshtml", model);
        }
        [HttpPost]
        public ActionResult Location(Browse model)
        {
            model.AllLocationOptions = db.BRANCH.OrderBy(s => s.BRANCH_NAME).ToList().Select(c => new SelectListItem()
            {
                Text = c.BRANCH_NAME,
                Value = c.BRANCH_NUM.ToString()
            });
            return PartialView("~/Views/Shared/_Location.cshtml", model);
        }
    }
}

ASP_Final/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net;
using System.Web.UI.WebControls.Expressions;
using ASP_Final.Models;

namespace ASP_Final.Controllers
{
    public class HomeController : Controller
    {
        private HenryEntities db = new HenryEntities();

        public ActionResult Index()
        {
            var allPublishers = db.PUBLISHER.ToList();
            List<PUBLISHER> result = new List<PUBLISHER>();

            foreach (var publisher in allPublishers)
            {
                PUBLISHER model = new PUBLISHER();
                model.PUBLISHER_NAME = publisher.PUBLISHER_NAME;
                model.PUBLISHER_CODE = publisher.PUBLISHER_CODE;

                model.BOOK = db.BOOK.Where(e => e.PUBLISHER_CODE == publisher.PUBLISHER_CODE).ToList();
                result.Add(model);
            }

            return View(result);
        }

        public ActionResult Contact()
        {
            return View();
        }

        [HttpPost]
        public JsonResult Contact(Contact model)
        {
            ViewBag.Message = "Info Saved";
            return Json(model);
        }

        public ActionResult Author()
        {
            return View();
        }

        public ActionResult AuthorNum(int? aNum)
        {
            List<AUTHOR> result = new List<AUTHOR>();
            if (aNum == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            AUTHOR author = db.AUTHOR.Find(aNum);

            if (author == null)
            {
                return HttpNotFound();
            }

            result.Add(author);
            //return to Partial View and pass it model
            return View("Author", result);
        }

        [HttpPost]
        public ActionResult Author(Browse fromBrowse)
        {
            var allAuthors = db.AUTHOR.ToList();
            List<AUTHOR> result = new List<AUTHOR>();

            foreach (var author in allAuthors)
            {
                AUTHOR model = new AUTHOR();
                model.AUTHOR_NUM = author.AUTHOR_NUM;
                model.AUTHOR_LAST = author.AUTHOR_LAST;
                model.AUTHOR_FIRST = author.AUTHOR_FIRST;
                model.WROTE = db.WROTE.Where(e=>e.AUTHOR_NUM == author.AUTHOR_NUM && e.AUTHOR_NUM.ToString() == fromBrowse.AuthorSelected).ToList();

                result.Add(model);
            }

            return View(result);

        }
        public ActionResult Publisher()
        {
            return View();
        }

        public ActionResult PublishCode(string code)
        {
            List<PUBLISHER> result = new List<PUBLISHER>();
            if (code == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            PUBLISHER publisher = db.PUBLISHER.Find(code);

            if (publisher == null)
            {
                return HttpNotFound();
            }

            result.Add(publisher);
            //return to Partial View and pass it model
            return View("Publisher", result);
        }

        
        [HttpPost]
        public ActionResult Publisher(Browse fromBrowse)
        {
            var allPublishers = db.PUBLISHER.ToList();
            List<PUBLISHER> result = new List<PUBLISHER>();

            foreach (var publisher in allPublishers)
            {
                PUBLISHER model = new PUBLISHER();
                model.PUBLISHER_NAME = publisher.PUBLISHER_NAME;
                model.PUBLISHER_CODE = publisher.PUBLISHER_CODE;


                IOrderedQueryable<BOOK> allBooks = from b in db.BOOK
                    where b.PUBLISHER_CODE == publisher.PUBLISHER_CODE
                    where (string.IsNullOrEmpty(fromBrowse.PublisherSelected) ||
                           b.PUBLISHER_CODE.Contains(fromBrowse.PublisherSelected))
                    orderby b.PUBLISHER_CODE
                    select b;

                model.BOOK = allBooks.ToList();
                result.Add(model);
            }

            return View(result);
        }


        public ActionResult Location()
        {
            return View();
        }
        public ActionResult LocationNum(int? bNum)
        {
            List<BRANCH> result = new List<BRANCH>();
            if (bNum == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            BRANCH branch = db.BRANCH.Find(bNum);

            if (branch == null)
            {
                return HttpNotFound();
            }

            result.Add(branch);
            //return to Partial View and pass it model
            return View("Location", result);
        }

        [HttpPost]
        public ActionResult Location(Browse fromBrowse)
        {
            var allLocations = db.BRANCH.ToList();
            List<BRANCH> result = new List<BRANCH>();

            foreach (var branch in allLocations)
            {
                BRANCH model = new BRANCH();
                model.BRANCH_LOCATION = branch.BRANCH_LOCATION;
                model.BRANCH_NAME = branch.BRANCH_NAME;
                model.BRANCH_NUM = branch.BRANCH_NUM;
                model.INVENTORY = db.INVENTORY.Where(e => e.BRANCH_NUM == branch.BRANCH_NUM && e.BRANCH_NUM.ToString() == fromBrowse.LocationSelected).ToList();
                result.Add(model);
            }

            return View(result);

        }

        public ActionResult Books()
        {
            var allPublishers = db.PUBLISHER.ToList();
            List<PUBLISHER> result = new List<PUBLISHER>();

            foreach (var publisher in allPublishers)
            {
                PUBLISHER model = new PUBLISHER();
                model.PUBLISHER_NAME = publisher.PUBLISHER_NAME;
                model.PUBLISHER_CODE = publisher.PUBLISHER_CODE;

                model.BOOK = db.BOOK.Where(e => e.PUBLISHER_CODE == publisher.PUBLISHER_CODE).ToList();
                result.Add(model);
            }

            return View(result);
        }
    }
}

ASP_Final/Views/Home/Author.cshtml
@using System.Activities.Statements
@using System.Web.UI.WebControls
@using WebGrease.Css.ImageAssemblyAnalysis
@using System.Globalization;
@using System.Web.DynamicData
@model IEnumerable<ASP_Final.Models.AUTHOR>
@{
    ViewBag.Title = "Browse by Author";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div id="main">
    <br />
    @Html.Action("Index", "Browse")

    @if (Model != null)
    {
        <table>
            <tr>
                <td>BOOK CODE</td>
                <td>TITLE</td>
                <td>TYPE</td>
                <td>PRICE</td>
                <td>PAPERBACK</td>
                <td>PUBLISHER</td>
            </tr>

            @foreach (var author in Model)
            {
                foreach (var wrote in author.WROTE)
                {
                    <tr>
                        <td><a href="~/BOOKs/Details/@wrote.BOOK.BOOK_CODE">@wrote.BOOK.BOOK_CODE</a></td>
                        <td>@wrote.BOOK.TITLE</td>
                        <td>@wrote.BOOK.TYPE</td>
                        <td>$@Math.Round(decimal.Parse(wrote.BOOK.PRICE.ToString()), 2)</td>
                        @if (@wrote.BOOK.PAPERBACK == "1")
                        {
                            <td>
                                Yes
                            </td>
                        }
                        else
                        {
                            <td>
                                No
                            </td>
                        }
                    <td>@Html.ActionLink(@wrote.BOOK.PUBLISHER.PUBLISHER_NAME, "PublishCode", "Home", new { code = wrote.BOOK.PUBLISHER_CODE }, null)</td>

                    </tr>
                }
            }
        </table>
    }
</div>

ASP_Final/Views/Home/Books.cshtml
@using System.Web.UI.WebControls
@using WebGrease.Css.ImageAssemblyAnalysis
@using System.Globalization;
@using System.Web.DynamicData
@model IEnumerable<ASP_Final.Models.PUBLISHER>
    @{
        ViewBag.Title = "Browse By Inventory";
        Layout = "~/Views/Shared/_Layout.cshtml";
    }

<div id="main">
    <div id="bbox">
            
        @foreach (var publisher in Model)
        {

            foreach (var book in publisher.BOOK)
            {
                <div class="books">
                    <a href="~/BOOKs/Details/@book.BOOK_CODE"><img src="~/Content/Images/@book.BOOK_CODE/thumb.jpg" style="width: 125px; height: 193px;"/></a>
                </div>
            }
        }

    </div>
</div>

ASP_Final/Views/Home/Contact.cshtml
@model ASP_Final.Models.Contact

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script>
        function ShowContact(conInfo) {
            var target = $("#conFrm");
            target.empty();

            if (!conInfo) {
                target.append("No data has been received.");
            }
        }

    </script>
}

@{
    ViewBag.Title = "Contact Management";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="wrapper">
        <h3>Share Your Comments with Management</h3>
        <div id="conFrm">
            @using (Ajax.BeginForm("Contact", "Home", new AjaxOptions
            {
                HttpMethod = "Post",
                InsertionMode = InsertionMode.Replace,
                LoadingElementId = "loading",
                LoadingElementDuration = 8000,
                OnSuccess = "ShowContact"

            }))
            {

                var branches = new List<SelectListItem>
                {
                    new SelectListItem { Text = "Please Select a Branch", Value = "" },
                    new SelectListItem { Text = "Henry Downtown", Value = "1" },
                    new SelectListItem { Text = "Henry On The Hill", Value = "2" },
                    new SelectListItem { Text = "Henry Brentwood", Value = "3" },
                    new SelectListItem { Text = "Henry Eastshore", Value = "4" }
                };

                <table>
                    <tr>
                        <td>
                            <label>First Name</label><br />
                            @Html.TextBoxFor(s => s.FName)
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <label>Last Name</label><br />
                            @Html.TextBoxFor(s => s.LName)
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <label>Email</label><br />
                            @Html.TextBoxFor(s => s.Email)
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <label>Confirm Email</label><br />
                            @Html.TextBoxFor(s => s.ConfirmEmail)
                        </td>
                    </tr>
                    <tr>

                        <td>
                            <label>Branch</label><br />
                            @Html.DropDownListFor(s => s.Branch, new SelectList(branches, "Value", "Text"))
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <label>Comments</label><br />
                            @Html.TextAreaFor(s => s.Comments)
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <input type="reset" value="Reset" />
                            <input type="submit" value="Save" />
                        </td>
                    </tr>
                </table>
            }
        </div>
        <div id="loading" style="display: none;">
            Thank you for sharing your comments with Henry's Bookstore Management. We will be in touch shortly via email.
        </div>
    
</div>

ASP_Final/Views/Home/Index.cshtml
@using System.Web.UI.WebControls
@using WebGrease.Css.ImageAssemblyAnalysis
@using System.Globalization;
@using System.Web.DynamicData
@model IEnumerable<ASP_Final.Models.PUBLISHER>
@{
    ViewBag.Title = "Home Page";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div id="main">
    <div class="homebox">
        <p>@Html.ActionLink("Browse Inventory", "Books", "Home")</p>
        <img src="~/Content/images/inventory.jpg" />
    </div>

    <div class="homebox">
        <p>@Html.ActionLink("Browse by Author", "Author", "Home")</p>
        <img src="~/Content/images/author.jpg" />
    </div>

    <div class="homebox">
        <p>@Html.ActionLink("Browse by Publisher", "Publisher", "Home")</p>
        <img src="~/Content/images/publisher.jpg" />
    </div>

    <div class="homebox">
        <p>@Html.ActionLink("Browse by Location", "Location", "Home")</p>
        <img src="~/Content/images/bookstore.jpg" />
    </div>
</div>

ASP_Final/Views/Home/Location.cshtml
@using System.Activities.Statements
@using System.Web.UI.WebControls
@using WebGrease.Css.ImageAssemblyAnalysis
@using System.Globalization;
@using System.Web.DynamicData
@model IEnumerable<ASP_Final.Models.BRANCH>
@{
    ViewBag.Title = "Browse by Location";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div id="main">
    <br/>
    @Html.Action("Location", "Browse")


    @if (Model != null)
    {
        var i = 0;
        <div id="bflex">
            <div id="b1">
                @foreach (var branch in Model)
                {
                    foreach (var inventory in branch.INVENTORY)
                    {
                        if (i == 0)
                        {
                            i = 1;
                            <table>
                                <tr>

                                    <td>
                                        BRANCH NUMBER
                                    </td>
                                    <td>
                                        @inventory.BRANCH_NUM
                                    </td>
                                </tr>
                                <tr>

                                    <td>
                                        BRANCH NAME
                                    </td>
                                    <td>
                                        @inventory.BRANCH.BRANCH_NAME
                                    </td>
                                </tr>
                                <tr>

                                    <td>
                                        NUMBER OF EMPLOYEES
                                    </td>
                                    <td>
                                        @inventory.BRANCH.NUM_EMPLOYEES
                                    </td>
                                </tr>
                            </table>
                        }
                    }
                }
            </div>
            <div id="b2">
                <table>
                    <tr>
                        <td>TITLE</td>
                        <td>QUANTITY ON HAND</td>
                    </tr>
                    @foreach (var branch in Model)
                    {
                        foreach (var inventory in branch.INVENTORY)
                        {

                            <tr>
                                <td><a href="~/BOOKs/Details/@inventory.BOOK_CODE">@inventory.BOOK.TITLE</a></td>
                                <td>@inventory.ON_HAND</td>
                            </tr>

                        }
                    }
                </table>
            </div>
        </div>
    }
</div>

ASP_Final/Views/Home/Publisher.cshtml
@using System.Activities.Statements
@using System.Web.UI.WebControls
@using WebGrease.Css.ImageAssemblyAnalysis
@using System.Globalization;
@using System.Web.DynamicData
@model IEnumerable<ASP_Final.Models.PUBLISHER>
@{
    ViewBag.Title = "Browse by Publisher";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div id="main">
    <br />
    @Html.Action("Publisher", "Browse")

    @if (Model != null)
    {
        <table>
            <tr>
                <td>BOOK CODE</td>
                <td>TITLE</td>
                <td>TYPE</td>
                <td>PRICE</td>
                <td>PAPERBACK</td>

            </tr>

            @foreach (var publisher in Model)
            {
                foreach (var book in publisher.BOOK)
                {
                    <tr>
                        <td><a href="~/BOOKs/Details/@book.BOOK_CODE">@book.BOOK_CODE</a></td>
                        <td>@book.TITLE</td>
                        <td>@book.TYPE</td>
                        <td>$@Math.Round(decimal.Parse(book.PRICE.ToString()), 2)</td>
                        @if (book.PAPERBACK == "1")
                        {
                            <td>
                                Yes
                            </td>
                        }
                        else
                        {
                            <td>
                                No
                            </td>
                        }

                    </tr>
                }
            }
        </table>
    }
</div>